# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - foospower-api

on:
  push:
    branches:
      - masterrrr
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: npm install, build, and test
      run: |
        cd Server
        npm install
        npm run build --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'foospower-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2f3a746d8bf74049b5cd959364f8a160 }}
        package: ./Server
